#!/usr/bin/env python

import os
import subprocess

test_build = ('test' in COMMAND_LINE_TARGETS)

# Set up environment
env = Environment(TOOLS=['default', 'go'], GOBUILDDIR='build')
env.VariantDir('build', 'src')

test_sources = []
def _add_test(source, test):
    if test_build:
        source.append(test)
    test_sources.append(test)

# Version info
def get_bzr_path():
    for path in os.environ['PATH'].split(os.path.pathsep):
        path = os.path.join(path, 'bzr')
        if os.path.exists(path):
            return path
    return None

def generate_buildversion(env, target, source):
    template = """\
// This file is automatically generated.
// DO NOT EDIT.
package buildversion

const Source = "bzr"
const RevNo = "{revno}"
const RevID = "{revision_id}"
const BranchNickname = "{branch_nick}"
const CleanWC = {clean}
"""
    bzr_path = get_bzr_path()
    f = open(str(target[0]), 'w')
    try:
        if bzr_path:
            subprocess.call([bzr_path, 'version-info', '--custom', '--template', template], stdout=f)
        else:
            template = template.replace('{revno}', 'archive')
            template = template.replace('{revision_id}', 'archive')
            template = template.replace('{branch_nick}', 'archive')
            template = template.replace('{clean}', '1')
            template = template.replace('bzr', 'archive')
            f.write(template)
    finally:
        f.close()

version_file = File('build/buildversion.go')
Command(version_file, [], generate_buildversion)
AlwaysBuild(version_file)

build_info_packages = [
    env.Go(version_file),
]

# Main build
root_packages = [
    env.Go('build/fmath.go'),
    env.Go('build/stack.go'),
]

goray_packages = [
    'background',
    'bound',
    'camera',
    'color',
    'integrator',
    #'kdtree',
    'light',
    'material',
    'matrix',
    'object',
    'partition',
    'primitive',
    'ray',
    'render',
    'scene',
    'surface',
    'vector',
    'vmap',
    'volume',
    'version',
]
goray_packages = [env.Go('build/goray/%s.go' % name) for name in goray_packages]

std_packages = [
    'integrators/trivial',
    'objects/mesh',
    'primitives/sphere',
]
std_packages = [env.Go('build/goray/std/%s.go' % name) for name in std_packages]

packages = build_info_packages + root_packages + goray_packages + std_packages
Alias('lib', packages)
Alias('core', root_packages + goray_packages)
Alias('std', std_packages)

program = env.GoProgram('bin/goray', 'build/main.go')

Default(packages + [program])

# Testing
#testenv = env.Clone(ENV=os.environ)
#testenv.GoTests('bin/_gotest.go', test_sources)
#test_package = testenv.Go('bin/_gotest.go')
#test_harness = testenv.GoProgram('bin/_gotest', [test_package] + packages)
#AlwaysBuild(testenv.Alias('test', [test_harness], 'bin/_gotest'))
#if test_build:
    #AlwaysBuild('bin/_gotest.go')
    #AlwaysBuild(test_harness)
    #AlwaysBuild(packages)
    #testenv.Decider('make')
