#!/usr/bin/env python

Import('env')

go_files = [
    'bound.go',
    'clip.go',
    'clip_test.go',
    'mesh.go',
    'triangle.go',
]
if env['ENV']['GOARCH'] == 'amd64' and env['SSE2']:
    go_files.append('intersect_decl.go')
else:
    go_files.append('intersect.go')
go_obj = env.Go('_go_', go_files)

lib_objects = [go_obj]
if env['ENV']['GOARCH'] == 'amd64' and env['SSE2']:
    lib_objects.append(env.GoAssembly('intersect_amd64.6', 'intersect_amd64.s'))

packages = [env.GoPack('../mesh.a', lib_objects)]
Return('packages')
