#!/usr/bin/env python

Import('env')

packages = [
    env.Go('background', Glob('background/*.go')),
    env.Go('bound', Glob('bound/*.go')),
    env.Go('camera', Glob('camera/*.go')),
    env.Go('color', Glob('color/*.go')),
    env.Go('integrator', Glob('integrator/*.go')),
    env.Go('intersect', Glob('intersect/*.go')),
    env.Go('kdtree', Glob('kdtree/*.go')),
    env.Go('light', Glob('light/*.go')),
    env.Go('material', Glob('material/*.go')),
    env.Go('matrix', Glob('matrix/*.go')),
    env.Go('object', Glob('object/*.go')),
    env.Go('photon', Glob('photon/*.go')),
    env.Go('primitive', Glob('primitive/*.go')),
    env.Go('ray', Glob('ray/*.go')),
    env.Go('render', Glob('render/*.go')),
    env.Go('scene', Glob('scene/*.go')),
    env.Go('surface', Glob('surface/*.go')),
    env.Go('vector', Glob('vector/*.go')),
    env.Go('vmap', Glob('vmap/*.go')),
    env.Go('volume', Glob('volume/*.go')),
]

Return('packages')
