#!/usr/bin/env python

Import('env')

packages = [
    env.Go('background'),
    env.Go('bound', Glob('bound/*.go')),
    env.Go('camera'),
    env.Go('color'),
    env.Go('integrator'),
    env.Go('kdtree', Glob('kdtree/*.go')),
    env.Go('light'),
    env.Go('material'),
    env.Go('matrix'),
    env.Go('object'),
    env.Go('partition', Glob('partition/*.go')),
    env.Go('photon'),
    env.Go('primitive'),
    env.Go('ray'),
    env.Go('render'),
    env.Go('scene'),
    env.Go('surface'),
    env.Go('vector', Glob('vector/*.go')),
    env.Go('vmap'),
    env.Go('volume'),
    env.Go('version'),
]

Return('packages')
