#!/usr/bin/env python

Import('env')

packages = [
    env.Go('integrators/directlight'),
    env.Go('integrators/trivial'),
    env.Go('lights/point'),
    env.Go('materials/debug'),
    env.Go('objects/mesh'),
    env.Go('primitives/sphere'),
]

Return('packages')
