#!/usr/bin/env python

Import('env')

packages = [
	env.Go('cameras/ortho'),
    env.Go('integrators/trivial'),
    env.Go('lights/point'),
    env.Go('objects/mesh'),
    env.Go('primitives/sphere'),
]

Return('packages')
