#!/usr/bin/env python

Import('env')

packages = [
    env.Go('cameras/ortho'),
    env.Go('cameras/perspective'),
    env.Go('integrators/directlight'),
    env.Go('integrators/trivial'),
    env.Go('integrators/util'),
    env.Go('lights/point'),
    env.Go('lights/spot'),
    env.Go('materials/common'),
    env.Go('materials/debug'),
    env.Go('materials/shinydiffuse'),
    env.Go('primitives/sphere'),
    env.Go('yamlscene', Glob('yamlscene/*.go')),
]

packages += SConscript('objects/mesh/SConscript', exports=['env'])

Return('packages')
