#!/usr/bin/env python

Import('env')

root_packages = [
    env.Go('logging', Glob('logging/*.go')),
    env.Go('montecarlo.go'),
    env.Go('time', Glob('time/*.go')),
    env.Go('stack', Glob('stack/*.go')),
    env.Go('version'),
]

subpackages = SConscript(['core/SConscript', 'std/SConscript'], exports='env')
packages = Flatten([root_packages, subpackages])

Return('packages')
