#!/usr/bin/env python

Import('env')

package = env.GoPack('../goray.a', env.Go('_go_', Glob('*.go')))

subpackages = [
    'bound',
    'color',
    'intersect',
    'job',
    'kdtree',
    'logging',
    'matrix',
    'montecarlo',
    'sampleutil',
    'server',
    'server/urls',
    'shader',
    'time',
    'vector',
]
subpackages = [
    env.GoPack(path + '.a', env.Go(path + '/_go_', env.Glob(path + '/*.go')))
    for path in subpackages
]

subtrees = SConscript(
    [
        'std/SConscript',
    ],
    exports='env',
)
packages = Flatten([package, subpackages, subtrees])

Return('packages')
