#!/usr/bin/env python

Import('env')

packages = [
	env.Go('data', Glob('data/*.go')),
	env.Go('parser', Glob('parser/*.go')),
    env.Go('scanner', Glob('scanner/*.go')),
    env.Go('token', Glob('token/*.go')),
]

Return('packages')
