//
//	yaml/tokens.go
//	goray
//
//	Created by Ross Light on 2010-06-24.
//

package yaml

const (
	NO_TOKEN = iota
	
	STREAM_START_TOKEN
	STREAM_END_TOKEN
	
    VERSION_DIRECTIVE_TOKEN
    TAG_DIRECTIVE_TOKEN
    DOCUMENT_START_TOKEN
    DOCUMENT_END_TOKEN

    BLOCK_SEQUENCE_START_TOKEN
    BLOCK_MAPPING_START_TOKEN
    BLOCK_END_TOKEN

    FLOW_SEQUENCE_START_TOKEN
    FLOW_SEQUENCE_END_TOKEN
    FLOW_MAPPING_START_TOKEN
    FLOW_MAPPING_END_TOKEN

    BLOCK_ENTRY_TOKEN
    FLOW_ENTRY_TOKEN
    KEY_TOKEN
    VALUE_TOKEN

    ALIAS_TOKEN
    ANCHOR_TOKEN
    TAG_TOKEN
    SCALAR_TOKEN
)
type Token int

type Position struct {
	Index int
	Line int
	Column int
}
